######################################################################
# Automatically generated by qmake (3.0) mar. avr. 17 09:57:41 2018
######################################################################

TEMPLATE = app
TARGET = ponge
INCLUDEPATH += .

# Input
HEADERS += Ball.hpp MainWindow.hpp Paddle.hpp Player.hpp Ponge.hpp
SOURCES += Ball.cpp main.cpp MainWindow.cpp Paddle.cpp Player.cpp Ponge.cpp
QT += widgets
